# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
    build:
        docker: # run the steps with Docker
            - image: circleci/node:10.16.3
        steps:
            - checkout
            - run: 'yarn install'
            - run: 'yarn build'
            - run:
                name: 'Run tests'
                command: 'yarn test --ci --runInBand --reporters=default --reporters=jest-junit'
                environment:
                    JEST_JUNIT_OUTPUT_DIR: "reports/junit"
            - store_test_results:
                path: reports/junit
            - store_artifacts:
                path: reports/junit
